### ISSUE TITLE
Error: Could not find all required packages:

### ISSUE THREAD

**Issue by phiresky** [Jguer/yay#319]
#### Affected Version

yay v5.608.r6.g5bf291b

#### Issue

yay -Syu returns
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Querying AUR...
==> Missing AUR Packages: libcloudproviders
==> Orphaned AUR Packages: j7 gnonlin gtkglextmm mist-classic musicbrainz gstreamer0.10-mm jd-core-java galapix dmenu-xft-mouse-height-fuzzy-history sk1libs
==> Out Of Date AUR Packages: intel-inspector dupeguru j7 intel-tbb_psxe pkgbuild-watch freenet spotify zotero intel-vtune-amplifier intel-fortran-compiler intel-mkl teamviewer intel-mpi intel-ipp adbfs-rootless-git qt-installer-framework phototonic dmenu-xft-mouse-height-fuzzy-history intel-advisor intel-compiler-base sk1libs ttf-impallari-cantora
==> Error: Could not find all required packages:
	java-runtime-headless>=8 java-runtime-headless<=8
	libcloudproviders
	java-environment>=8 java-environment<=8
```

The same situation works fine on pacaur.
I'm not sure which package is actually having problems.

I have both  `jdk` (10) and `extra/jre8-openjdk` installed, which provides `java-environment=8  java-environment-openjdk=8` (and jre8-openjdk-headless which provides java-runtime-headless=8`)

I'm guessing this is an issue since the new version checking because I have both `java-runtime-headless=10` and `java-runtime-headless=8` installed and yay only sees the frist?

**Comment by phiresky** [comment]
Confirmed, it works fine if I remove `jdk`. So to reproduce install both `jdk` and `jre8-openjdk`

**Comment by Morganamilo** [comment]
Hey I think I've fixed this, it's a little hard to tell with the limited versioned deps out there to test against. I'm guessing you already did the update so you can't test right now. Just be on the look out to see if it happens again and thanks for reporting.

**Comment by josswright** [comment]
Hi,

I've just found this bug, and am still having this problem with the latest yay-git.

I've just transitioned three systems from pacaur to yay, but on one of them I'm getting:

```
:: Querying AUR...
 -> Missing AUR Packages:  openssl
 -> Out Of Date AUR Packages:  advcp
==> Error: Could not find all required packages:
    openssl
```

When I run `yay -Syu`.

**Comment by Morganamilo** [comment]
That seems weird can you tell me what what what being updated?

**Comment by josswright** [comment]
I also uninstalled openssl and reinstalled, just to make sure that something odd hadn't happened with that.

**Comment by Morganamilo** [comment]
Uh you still seem to be missing the upgrade list.

**Comment by josswright** [comment]
```
joss@poe:~$ yay -Su --devel
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
:: Querying AUR...
 -> Missing AUR Packages:  openssl
 -> Out Of Date AUR Packages:  advcp
==> Error: Could not find all required packages:
    openssl
```

**Comment by Morganamilo** [comment]
I mean the packages that need to be upgraded. Try `yay -Qu --devel`.

**Comment by josswright** [comment]
Ah... that gives me a much longer list. I had assumed that there were no updates due.

I'll have a play here now and see if there's something specific causing this. (This is a fairly established install, so has lots of packages installed.)

**Comment by josswright** [comment]
Sure. For reference, after cleaning out some old cruft packages it's now apparently working. Sorry if I've spoiled a potentially useful bug.

I've attached the original `yay -Qu --devel` output.
[yay-qu.txt](https://github.com/Jguer/yay/files/1975091/yay-qu.txt)

**Comment by Morganamilo** [comment]
I tracked it down to `scamper` now to figure out why exactly.

**Comment by elbaro** [comment]
Just installed yay and having the same problem.

pacaur and trizen simply asks for the update confirmation, but yay complains.

```
❯ yay -Syu
..
:: Searching databases for updates...
:: Searching AUR for updates...
:: Querying AUR...
==> Error: Could not find all required packages:
    nvidia-utils>=1:390.48 nvidia-utils<=1:390.48

❯ pacman -Qe | grep nvidia-utils
lib32-nvidia-utils 1:390.48-1
nvidia-utils 1:390.48-1

❯ yay -Qu --devel | grep nvidia
linux414-nvidia 1:390.48-4 -> 1:390.48-6
```

**Comment by Morganamilo** [comment]
There does seem to be something wrong there.

Is `linux414-nvidia` from a custom repo? Could you give me a `-Si` on it?

You might want to try doing `-Syud` as a work around to avoid the version checks.

**Comment by elbaro** [comment]
Manjaro has its own version of graphic drivers.

```
❯ LANG=en_US.UTF8 pacman -Si linux414-nvidia
Repository      : extra
Name            : linux414-nvidia
Version         : 1:390.48-6
Description     : NVIDIA drivers for linux.
Architecture    : x86_64
URL             : http://www.nvidia.com/
Licenses        : custom
Groups          : linux414-extramodules
Provides        : nvidia=390.48
Depends On      : linux414  nvidia-utils=1:390.48
Optional Deps   : None
Conflicts With  : nvidia-96xx  nvidia-173xx
Replaces        : None
Download Size   : 9.02 MiB
Installed Size  : 9.20 MiB
Packager        : Philip Mueller <philm@manjaro.org>
Build Date      : None
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
```
❯ LANG=en_US.UTF8 pacman -Si nvidia-utils
Repository      : extra
Name            : nvidia-utils
Version         : 1:390.48-1
Description     : NVIDIA drivers utilities
Architecture    : x86_64
URL             : http://www.nvidia.com/
Licenses        : custom
Groups          : None
Provides        : vulkan-driver  opengl-driver  nvidia-libgl  nvidia-utils=390.48
Depends On      : xorg-server  libglvnd  mhwd
Optional Deps   : gtk2: nvidia-settings
                  xorg-server-devel: nvidia-xconfig
                  opencl-nvidia: OpenCL support
Conflicts With  : nvidia-libgl
Replaces        : nvidia-libgl
Download Size   : 23.37 MiB
Installed Size  : 109.32 MiB
Packager        : Philip Mueller <philm@manjaro.org>
Build Date      : None
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```
```
❯ yay -S linux414-nvidia
==> Error: Could not find all required packages:
    nvidia-utils>=1:390.48 nvidia-utils<=1:390.48
```
```
❯ LANG=en_US.UTF8 pacaur -S linux414-nvidia
warning: linux414-nvidia-1:390.48-6 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
Packages (1) linux414-nvidia-1:390.48-6
Total Installed Size:  9.20 MiB
Net Upgrade Size:      0.00 MiB
:: Proceed with installation? [Y/n]
```

**Comment by Morganamilo** [comment]
It seems like Yay thinks that `1:390.48-6` is not in the range `nvidia-utils>=1:390.48 nvidia-utils<=1:390.48` Maybe it's the -6 I have not accounted for.

Either way this is kind of hard to test for myself because it's not in the Arch repos.

I have started a rewrite of the dependency that I mentioned a while ago, should fix all the stuff like this.

In the mean time, if you're sure it should install, "-d" might remove the error.

**Comment by StephenBrown2** [comment]
Found another issue like this running yay v6.727 and trying to update vscode, possibly a feature request:

`yay` displays the ambiguous error:
```
==> Error: Could not find all required packages:
  nodejs<10.0
```

`pikaur` displays the package with the unsatisfyable dep:
```
Resolving AUR dependencies...
Version mismatch:
*code* depends on: 'nodejs<10.0'
 found in 'PackageSource.REPO': '10.1.0-1'
```

I worked around the problem by installing `nodejs-latest-bin 9.11.0-1` from the aur, updating `code`, then reinstalling `npm` and `nodejs`.

**Comment by Morganamilo** [comment]
That looks like a valid case where this should trigger. `nodejs-10.1.0-1` exists but code wants `<10.0`.

If it's the error text you're complaining about #401 should give a better error message. Although it seems like you fixed it already anyway.

**Comment by StephenBrown2** [comment]
Yeah, it was more for the error text. I didn't know what was requiring the older version of `nodejs` until I ran `pikaur`, which pointed me right at `code`, so I'm happy with the changes being done in #401, and have built that version to use for now on my system. :+1:

**Comment by Morganamilo** [comment]
>built that version to use for now on my system

It seems so work but be warned it's still in the testing phase. If you have problems it feel free to leave comments on the PR.

**Comment by StephenBrown2** [comment]
Noted. Will do.

**Comment by solarkraft** [comment]
Hi, I think I'm stumbling upon a similar or the same problem with `yay v10.0.1 - libalpm v12.0.2` while trying to install `electron-ozone` (or really anything else requiring `gn`): 

```
$ pacman -Q gn
gn 0.1819.e327ffdc-1
$ yay -S electron-ozone
:: There are 22 providers available for java-runtime-headless:
:: Repository extra
    1) jre-openjdk-headless 2) jre11-openjdk-headless 3) jre7-openjdk-headless 4) jre8-openjdk-headless 
:: Repository disastrousaur
    5) java-openjdk-bin 6) java-openjdk-ea-bin 7) jdk-openj9-bin 8) jdk12-openj9-bin 9) jdk13-openj9-bin 10) jdk14-openj9-bin 11) jdk6 12) jdk7 13) jdk7-j9-bin 14) jdk7r1-j9-bin 15) jdk8-openj9-bin 16) jdk9 17) jdk9-openj9-bin 18) jre 19) jre6 20) jre7 21) jre8 22) jre9 

Enter a number (default=1): 
 -> Could not find all required packages:
        gn<0.1809 (Wanted by: electron-ozone)
```
