### ISSUE TITLE
AUR update fails with large number of packages

### ISSUE THREAD

**Issue by wbthomason** [Jguer/yay#59]
I have a very large number of AUR packages installed on my machine (most of them from https://aur.archlinux.org/packages/ros-lunar-desktop-full/, which is massive). When I try `yay -Syu` to update all packages (AUR and official repos), the `GET` request to the AUR RPC fails: The server closes the connection, sends `GOAWAY`, and gives error code `ENHANCE_YOUR_CALM` (as a side note, I was very pleased to discover that HTTP/2 has these wonderful error codes).

I haven't been able to debug this at all yet, but I would presume that it occurs because `yay` makes a single query for all packages. Perhaps making several queries limited at a certain number of packages each would be more robust?

For what it's worth, I've been using `yaourt` and `pacaur` with no trouble with the same set of packages.

**Comment by Jguer** [comment]
Seems like a follow up of https://github.com/Jguer/yay/issues/34 , yay already splits the requests

Quoting rmarquis:
```
The maximum defined isn't directly related to the number of packages, but to the total length of the URL request. I've empirically determined that curl returns an error code 56 (CURLE_RECV_ERROR) with any RPC request that has more than 4443 characters, so you can check that instead of the number of package if you want to try to minimize the number of sub-requests sent (that is about to ~200 to ~250 packages, but YMMV).
```

Could be related. Have you tried changing your `~/.config/yay/config.json` `requestsplitn` to a lower value?

**Comment by wbthomason** [comment]
Whoops, I missed that issue when I checked to see if this was a known
problem. I'll try that config change.

**Comment by wbthomason** [comment]
Even for pathologically low settings of that value (e.g. 1, 2) still produce the same behavior, although more requests are made. It is as if the full package list is being used in every request.

**Comment by Jguer** [comment]
Definitely something changed in the built code's behaviour from past versions. Yay is submitting the same request many times. 

Turns out it was a refactoring typo. Please test the next commit, it should fix the problem.

**Comment by wbthomason** [comment]
I just tried the new `yay` package (v2.219), and still see the same behavior.
